package com.example.disastermanagement.controller;

import com.example.disastermanagement.model.SosRequest;
import com.example.disastermanagement.service.RescueTeamService;
import com.example.disastermanagement.service.SosService;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/admin/sos")
public class AdminSosController {

    private final SosService sosService;
    private final RescueTeamService rescueTeamService;

    public AdminSosController(SosService sosService, RescueTeamService rescueTeamService) {
        this.sosService = sosService;
        this.rescueTeamService = rescueTeamService;
    }

    @GetMapping
    public List<SosRequest> list(
            @RequestParam(required = false) String email,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate start,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate end
    ) {
        return sosService.search(email, start, end);
    }

    @GetMapping("/all")
    public List<SosRequest> getAllSos() {
        return sosService.getAll();
    }

    /**
     * STEP 11E: Get all auto-generated SOS requests.
     * 
     * Returns only SOS entries that were automatically generated by the system
     * (e.g., triggered by high-severity weather alerts).
     * 
     * @return List of auto-generated SOS requests, ordered by timestamp descending
     */
    @GetMapping("/auto")
    public List<SosRequest> getAutoGeneratedSos() {
        return sosService.getAutoGeneratedSos();
    }

    @PatchMapping("/{id}/start")
    public SosRequest markInProgress(@PathVariable long id) {
        return sosService.markInProgress(id);
    }

    @PatchMapping("/{id}/resolve")
    public SosRequest markResolved(@PathVariable long id) {
        return sosService.markResolved(id);
    }

    @PostMapping("/{id}/assign/{teamId}")
    public SosRequest assignTeam(@PathVariable long id, @PathVariable long teamId) {
        rescueTeamService.updateAvailability(teamId, false);
        return sosService.assignTeam(id, teamId);
    }
}
