package com.example.disastermanagement.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SosRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String userEmail;
    private double latitude;
    private double longitude;
    private String message;
    private String type;

    @Builder.Default
    private String status = "PENDING";

    private LocalDateTime timestamp;

    private Long assignedTeamId;

    @Builder.Default
    private boolean autoGenerated = false; // true for auto-SOS, false for manual SOS
}
